version: "3.5"

services:
  # for VSCode Dev Container
  work:
    build:
      context: "."
      dockerfile: Dockerfile
    working_dir: "/work/"
    command: [ "sleep", "infinity" ]
    volumes:
      - "./:/work/:delegated"
    environment:
      - SPANNER_EMULATOR_HOST=spanner:9010

  # for GoLand with JetBrains Gateway
  work-remote:
    build:
      context: "."
      dockerfile: Dockerfile
      target: work-remote
    working_dir: "/work/"
    command:
      [
        "/usr/sbin/sshd",
        "-D",
        "-e",
        "-f",
        "/etc/ssh/sshd_config_test_goland"
      ]
    volumes:
      - "./:/work/:delegated"
    ports:
      - "127.0.0.1:2222:22"
    #  - "8080:80"

  # to test implementation for spanner
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
  gcloud:
    platform: linux/amd64
    image: asia.gcr.io/google.com/cloudsdktool/google-cloud-cli
    depends_on:
      - spanner
    environment:
      - SPANNER_EMULATOR_HOST=spanner:9010
    volumes:
      - ./:/work
    working_dir: /work